name: Perform linting

on:
  workflow_call:
  push:
    branches:
      - main
      - develop

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Setup node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install biome
      - name: Install Biome
        run: yarn install @biomejs/biome

      # Run linter
      - name: Lint
        run: yarn lint

